from typing import Protocol
import torch


class FieldModule(Protocol):
    name: str
    def electric_field(self, positions: torch.Tensor, time: float) -> torch.Tensor: ...
    def magnetic_field(self, positions: torch.Tensor, time: float) -> torch.Tensor: ...
    def scene_renderers(self) -> list[object]: ...
    def state_dict(self) -> dict: ...
    def load_state_dict(self, state: dict) -> None: ...
