from typing import Protocol
import torch


class Domain(Protocol):
    grid_shape: tuple[int, int, int]
    bounds: tuple[tuple[float, float], tuple[float, float], tuple[float, float]]

    def interior_mask(self, device: torch.device, dtype: torch.dtype) -> torch.Tensor: ...
    def particle_inside(self, positions: torch.Tensor) -> torch.Tensor: ...
    def boundary_types(self, positions: torch.Tensor) -> list[str]: ...
    def scene_renderers(self) -> list[object]: ...
